server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: harriet
    password: harriet
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always  # Options: always, embedded, never, should not use in prod

  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis # no plain password in prod, inject from env

queue:
  transaction-request: transaction.request.queue

redis:
  address: redis://127.0.0.1:6379
#settings:
#  transfer:
#    maximum: 1000000